POST http://localhost:3500/users/add/admin
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "username": "admin",
    "password": "12345678"
   
}


###
POST http://localhost:3500/workshift/add
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "nameWork": "Ca 3",
    "start_time": "2023-11-18T19:00:00",
    "end_time": "2023-11-19T22:00:00"
}

###
POST http://localhost:3500/messageData/deleteAllNoti
Content-Type: application/json


###
GET http://localhost:3500/products





###
GET http://localhost:3500/users



###
POST http://localhost:3500/order/createOrder
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "tableNumber": 1,
    "productId": "646a432b2966f6cadbf0d144",
    "location":"609/88/99 tây ninh",
    "status": "",
    "isPaid" : false,
    "isCancelled":false
}


###
POST http://localhost:3500/order/getAllOrderByLocation
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "location":"409/99 Tân chánh hiệp 12 quận 12 TP.HCM"
}



###
POST http://localhost:3500/order/getAllByLocationSocket
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "location" : "409/99 Tân chánh hiệp 12 quận 12 TP.HCM"
}



###
POST http://localhost:3500/order/getAllOrderByNumberTable
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "tableNumber" : 1
}



###
GET http://localhost:3500/order/getAll


###
GET http://localhost:3500/order/getProductByIdLocationUser/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NTAzNTg5ODJ9.AHmRNgtATHFwZ1Uh7mK8_ezOImVgVv7nYtJSW5b9mEg

// tâm -  location: 403 châu thành tây ninh - general 30 QR code - user order -> tâm: bàn số 1, nước ngọt
// điều kiện render:
//  - dựa vào location để render list (bàn order, sản phẩm order, thời gian đặt)
//  - user behavior (order - send message - render realtime list item order at admin page)

###
POST http://localhost:3500/auth/login
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxMThkNTdkOWFhYmZhNmM4MzM4ZmMiLCJpYXQiOjE2NDk0NzMwNzl9.MaFbQnCgm3GyXvHV1wgfxzonf0Lc8wFiKp-hiR-dLyo


{
    "username": "vu tri tam",
    "password": "12345678"
}
